server:
  port: 8082

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: accounts-examiner

  boot:
    admin:
      client:
        enabled: false
#        instance:
#          name: accounts-examiner
#          service-host-type: ip
#        url: http://localhost:8085

services:
  examiner:
    fixed-delay: 10
    initial-delay: 5
    threshold: 1

  external:
    url:  https://api.coinlore.net/api/ticker

  internal:
#    url: http://localhost:8081/api/v1
    url: lb://accounts-service/api/v1

  mail-sender:
#    url: http://localhost:8083/api/v1
    url: lb://accounts-mailsender/api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



