server:
  port: 8082

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: accounts-examiner

  boot:
    admin:
      client:
        enabled: false
#        instance:
#          name: accounts-examiner
#          service-host-type: ip
#        url: http://host.docker.internal:8085

services:
  examiner:
    fixed-delay: 10
    initial-delay: 5
    threshold: 1

  external:
    url: https://api.coinlore.net/api/ticker

  internal:
    url: lb://accounts-service//api/v1
#    url: http://host.docker.internal:8081/api/v1
#    url: http://localhost:8081/api/v1

  mail-sender:
    url: lb://accounts-mailsender/api/v1
#    url: http://host.docker.internal:8083/api/v1
#    url: http://localhost:8083/api/v1






