server:
  port: 8081

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: accounts-service

  boot:
    admin:
      client:
        enabled: false
#        instance:
#          name: accounts-service
#          service-host-type: ip
#        url: http://localhost:8085

  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: accounts
    password: accounts
    driverClassName: org.postgresql.Driver

#  datasource:
#    url: ${datasource.url:jdbc:postgresql://localhost:5432/accounts}
#    username: ${datasource.username:accounts}
#    password: ${datasource.password:accounts}
#    driverClassName: org.postgresql.Driver

  flyway:
    schemas:
      - public
      - accounts

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true